In [2]:
import pandas as pd 
import numpy as np 
import matplotlib as plt

In [4]:
cancer_df = pd.read_excel("AIHW_CancerINFO_2023.xlsx",sheet_name="Table S2a.1")

In [5]:
cancer_df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Table S2a.1: Cancer mortality counts from the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Data type,Cancer group/site,Year,Sex,Age group (years),Count,"Age-specific rate\n(per 100,000)",Age-standardised rate\n2001 Australian Standar...,Age-standardised rate\n2023 Australian populat...,"Age-standardised rate\n (WHO) (per 100,000)","Age-standardised rate\n (Segi) (per 100,000)",NaN,ICD10 codes

In [6]:
cancer_df = cancer_df.iloc[4:].reset_index(drop=True)

In [11]:
cancer_df = cancer_df.rename(columns = cancer_df.iloc[0]).iloc[1:]

In [12]:
cancer_df.head()

,Data type,Cancer group/site,Year,Sex,Age group (years),Count,"Age-specific rate\n(per 100,000)","Age-standardised rate\n2001 Australian Standard Population (per 100,000)","Age-standardised rate\n2023 Australian population \n(per 100,000)","Age-standardised rate\n (WHO) (per 100,000)","Age-standardised rate\n (Segi) (per 100,000)",NaN,ICD10 codes
1,Actual,Acute lymphoblastic leukaemia,1971,Males,00–04,21,3.3,. .,. .,. .,. .,,C91.0
2,Actual,Acute lymphoblastic leukaemia,1971,Males,05–09,24,3.8,. .,. .,. .,. .,,C91.0
3,Actual,Acute lymphoblastic leukaemia,1971,Males,10–14,11,1.7,. .,. .,. .,. .,,C91.0
4,Actual,Acute lymphoblastic leukaemia,1971,Males,15–19,2,0.3,. .,. .,. .,. .,,C91.0
5,Actual,Acute lymphoblastic leukaemia,1971,Males,20–24,3,0.5,. .,. .,. .,. .,,C91.0

In [14]:
cancer_df['ICD10 codes'].value_counts()

ICD10 codes
C91.0                                      3180
C30.0                                      3180
C26 (NMD mortality data excludes C26.0)    3180
C09–C10                                    3180
C00–C10                                    3180
                                           ...
C94.3, C96                                 1620
C37–C39                                    1620
C90.1–C90.9                                1620
C54.1                                      1080
C93.1, C93.3                                540
Name: count, Length: 96, dtype: int64

In [52]:
skin_cancer_df = cancer_df[cancer_df['ICD10 codes'].str.startswith(('C43','C44'), na=False)]

In [53]:
skin_cancer_df['Cancer group/site'].value_counts()

Cancer group/site
Melanoma of the skin                    3180
Non-melanoma skin cancer (all types)    3180
Name: count, dtype: int64

In [54]:
skin_cancer_df.shape

(6360, 13)

In [55]:
skin_cancer_df.columns

Index([                                                               'Data type',
                                                              'Cancer group/site',
                                                                           'Year',
                                                                            'Sex',
                                                              'Age group (years)',
                                                                          'Count',
                                               'Age-specific rate\n(per 100,000)',
       'Age-standardised rate\n2001 Australian Standard Population (per 100,000)',
              'Age-standardised rate\n2023 Australian population \n(per 100,000)',
                                    'Age-standardised rate\n (WHO) (per 100,000)',
                                   'Age-standardised rate\n (Segi) (per 100,000)',
                                                                              nan,
                                                                    'ICD10 codes'],
      dtype='object')

In [56]:
skin_cancer_df.drop(skin_cancer_df.columns[11], inplace=True,axis = 1)

/var/folders/sk/qvmnp7x12fl7k3qd3ldd3cd40000gn/T/ipykernel_37942/3352439507.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  skin_cancer_df.drop(skin_cancer_df.columns[11], inplace=True,axis = 1)

In [57]:
skin_cancer_df.drop(skin_cancer_df.columns[6:11], inplace=True,axis = 1)

/var/folders/sk/qvmnp7x12fl7k3qd3ldd3cd40000gn/T/ipykernel_37942/2404338606.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  skin_cancer_df.drop(skin_cancer_df.columns[6:11], inplace=True,axis = 1)

In [58]:
skin_cancer_df.head()

,Data type,Cancer group/site,Year,Sex,Age group (years),Count,ICD10 codes
111041,Actual,Melanoma of the skin,1971,Males,00–04,1,C43
111042,Actual,Melanoma of the skin,1971,Males,05–09,0,C43
111043,Actual,Melanoma of the skin,1971,Males,10–14,1,C43
111044,Actual,Melanoma of the skin,1971,Males,15–19,2,C43
111045,Actual,Melanoma of the skin,1971,Males,20–24,3,C43

In [59]:
skin_cancer_df = skin_cancer_df[skin_cancer_df['Data type']!= 'Predictions']

In [60]:
skin_cancer_df.shape

(6360, 7)

In [61]:
skin_cancer_df.to_csv('skin_cancer_data.csv', index=False)

In [3]:
from sqlalchemy import create_engine

# 1. Your Neon connection details
# Replace with your actual string from the Neon Console
CONN_STR = "postgresql://neondb_owner:npg_RzbAnxIu37MU@ep-curly-union-a7s53hm8-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

# 2. Load your cleaned CSV
df = pd.read_csv("skin_cancer_data.csv")

# 3. Create the SQLAlchemy engine
engine = create_engine(CONN_STR)

# 4. Upload the data
# name: the table name in Neon
# if_exists: 'replace' creates a new table; 'append' adds to an existing one
df.to_sql(name='cancer_stats', con=engine, if_exists='replace', index=False)

print("Upload Complete! Check your Neon Console SQL Editor.")

Upload Complete! Check your Neon Console SQL Editor.