In [1]:
import pandas as pd 
import numpy as np 
import matplotlib as plt

In [4]:
cancer_df = pd.read_excel("AIHW_CancerINFO_2023.xlsx",sheet_name="Table S2a.1")

In [5]:
cancer_df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Table S2a.1: Cancer mortality counts from the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Data type,Cancer group/site,Year,Sex,Age group (years),Count,"Age-specific rate\n(per 100,000)",Age-standardised rate\n2001 Australian Standar...,Age-standardised rate\n2023 Australian populat...,"Age-standardised rate\n (WHO) (per 100,000)","Age-standardised rate\n (Segi) (per 100,000)",NaN,ICD10 codes

In [6]:
cancer_df = cancer_df.iloc[4:].reset_index(drop=True)

In [11]:
cancer_df = cancer_df.rename(columns = cancer_df.iloc[0]).iloc[1:]

In [12]:
cancer_df.head()

,Data type,Cancer group/site,Year,Sex,Age group (years),Count,"Age-specific rate\n(per 100,000)","Age-standardised rate\n2001 Australian Standard Population (per 100,000)","Age-standardised rate\n2023 Australian population \n(per 100,000)","Age-standardised rate\n (WHO) (per 100,000)","Age-standardised rate\n (Segi) (per 100,000)",NaN,ICD10 codes
1,Actual,Acute lymphoblastic leukaemia,1971,Males,00–04,21,3.3,. .,. .,. .,. .,,C91.0
2,Actual,Acute lymphoblastic leukaemia,1971,Males,05–09,24,3.8,. .,. .,. .,. .,,C91.0
3,Actual,Acute lymphoblastic leukaemia,1971,Males,10–14,11,1.7,. .,. .,. .,. .,,C91.0
4,Actual,Acute lymphoblastic leukaemia,1971,Males,15–19,2,0.3,. .,. .,. .,. .,,C91.0
5,Actual,Acute lymphoblastic leukaemia,1971,Males,20–24,3,0.5,. .,. .,. .,. .,,C91.0

In [14]:
cancer_df['ICD10 codes'].value_counts()

ICD10 codes
C91.0                                      3180
C30.0                                      3180
C26 (NMD mortality data excludes C26.0)    3180
C09–C10                                    3180
C00–C10                                    3180
                                           ...
C94.3, C96                                 1620
C37–C39                                    1620
C90.1–C90.9                                1620
C54.1                                      1080
C93.1, C93.3                                540
Name: count, Length: 96, dtype: int64

In [52]:
skin_cancer_df = cancer_df[cancer_df['ICD10 codes'].str.startswith(('C43','C44'), na=False)]

In [53]:
skin_cancer_df['Cancer group/site'].value_counts()

Cancer group/site
Melanoma of the skin                    3180
Non-melanoma skin cancer (all types)    3180
Name: count, dtype: int64

In [54]:
skin_cancer_df.shape

(6360, 13)

In [55]:
skin_cancer_df.columns

Index([                                                               'Data type',
                                                              'Cancer group/site',
                                                                           'Year',
                                                                            'Sex',
                                                              'Age group (years)',
                                                                          'Count',
                                               'Age-specific rate\n(per 100,000)',
       'Age-standardised rate\n2001 Australian Standard Population (per 100,000)',
              'Age-standardised rate\n2023 Australian population \n(per 100,000)',
                                    'Age-standardised rate\n (WHO) (per 100,000)',
                                   'Age-standardised rate\n (Segi) (per 100,000)',
                                                                              nan,
                                                                    'ICD10 codes'],
      dtype='object')

In [56]:
skin_cancer_df.drop(skin_cancer_df.columns[11], inplace=True,axis = 1)

/var/folders/sk/qvmnp7x12fl7k3qd3ldd3cd40000gn/T/ipykernel_37942/3352439507.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  skin_cancer_df.drop(skin_cancer_df.columns[11], inplace=True,axis = 1)

In [57]:
skin_cancer_df.drop(skin_cancer_df.columns[6:11], inplace=True,axis = 1)

/var/folders/sk/qvmnp7x12fl7k3qd3ldd3cd40000gn/T/ipykernel_37942/2404338606.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  skin_cancer_df.drop(skin_cancer_df.columns[6:11], inplace=True,axis = 1)

In [58]:
skin_cancer_df.head()

,Data type,Cancer group/site,Year,Sex,Age group (years),Count,ICD10 codes
111041,Actual,Melanoma of the skin,1971,Males,00–04,1,C43
111042,Actual,Melanoma of the skin,1971,Males,05–09,0,C43
111043,Actual,Melanoma of the skin,1971,Males,10–14,1,C43
111044,Actual,Melanoma of the skin,1971,Males,15–19,2,C43
111045,Actual,Melanoma of the skin,1971,Males,20–24,3,C43

In [59]:
skin_cancer_df = skin_cancer_df[skin_cancer_df['Data type']!= 'Predictions']

In [60]:
skin_cancer_df.shape

(6360, 7)

In [61]:
skin_cancer_df.to_csv('skin_cancer_data.csv', index=False)

In [55]:
from sqlalchemy import create_engine

# 1. Your Neon connection details
# Replace with your actual string from the Neon Console
CONN_STR = "postgresql://neondb_owner:npg_RzbAnxIu37MU@ep-curly-union-a7s53hm8-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

# 2. Load your cleaned CSV

In [ ]:

df = pd.read_csv("skin_cancer_data.csv")

# 3. Create the SQLAlchemy engine
engine = create_engine(CONN_STR)

# 4. Upload the data
# name: the table name in Neon
# if_exists: 'replace' creates a new table; 'append' adds to an existing one
df.to_sql(name='cancer_stats', con=engine, if_exists='replace', index=False)

print("Upload Complete! Check your Neon Console SQL Editor.")

Upload Complete! Check your Neon Console SQL Editor.

In [30]:
abs_stat_sunburn = pd.read_csv("Proportion of people 15 years and over who experienced sunburn in the last week by state and territory, Nov 2023 to Feb 2024.csv")

In [31]:
abs_stat_sunburn

                         Region  Proportion (%)
0               New South Wales             6.1
1                      Victoria             7.5
2                    Queensland             7.4
3               South Australia             5.5
4             Western Australia             7.0
5                      Tasmania            11.3
6            Northern Territory             4.9
7  Australian Capital Territory             6.2

In [28]:
abs_stat_tan = pd.read_csv("Proportion of people 15 years and over who attempted suntanning(a) by state and territory, Nov 2023 to Feb 2024.csv")

In [29]:
abs_stat_tan

                         Region  Proportion (%)
0               New South Wales            10.9
1                      Victoria             9.6
2                    Queensland             7.9
3               South Australia             7.1
4             Western Australia             8.5
5                      Tasmania            10.1
6            Northern Territory             4.2
7  Australian Capital Territory             9.6

In [39]:
population_df = pd.read_csv("Annual population change at 30 June 2024.csv")

In [40]:
population_df

,Region,Population at 30 June 2024 ('000),Change over previous year ('000),Change over previous year (%)
0,New South Wales,8484.4,143.2,1.7
1,Victoria,6981.4,165.1,2.4
2,Queensland,5586.3,125.8,2.3
3,South Australia,1878.0,25.1,1.4
4,Western Australia,2965.2,81.4,2.8
5,Tasmania,575.4,1.6,0.3
6,Northern Territory,255.1,2.0,0.8
7,Australian Capital Territory,474.1,7.8,1.7
8,Australia (a),27204.8,552.0,2.1

In [41]:
population_df = population_df[:-1]

In [42]:
population_df

,Region,Population at 30 June 2024 ('000),Change over previous year ('000),Change over previous year (%)
0,New South Wales,8484.4,143.2,1.7
1,Victoria,6981.4,165.1,2.4
2,Queensland,5586.3,125.8,2.3
3,South Australia,1878.0,25.1,1.4
4,Western Australia,2965.2,81.4,2.8
5,Tasmania,575.4,1.6,0.3
6,Northern Territory,255.1,2.0,0.8
7,Australian Capital Territory,474.1,7.8,1.7

In [43]:
population_df = population_df.drop(population_df.columns[[2,3]], axis=1)  # Drops the first 2 columns

In [44]:
suntan_sunburn_df = pd.merge(abs_stat_sunburn, abs_stat_tan, on=['Region'], suffixes=('_sunburn', '_tan'))

In [45]:
suntan_sunburn_df

                         Region  Proportion (%)_sunburn  Proportion (%)_tan
0               New South Wales                     6.1                10.9
1                      Victoria                     7.5                 9.6
2                    Queensland                     7.4                 7.9
3               South Australia                     5.5                 7.1
4             Western Australia                     7.0                 8.5
5                      Tasmania                    11.3                10.1
6            Northern Territory                     4.9                 4.2
7  Australian Capital Territory                     6.2                 9.6

In [46]:
chart_2_df = pd.merge(suntan_sunburn_df, population_df, on=['Region'])

In [47]:
chart_2_df

,Region,Proportion (%)_sunburn,Proportion (%)_tan,Population at 30 June 2024 ('000)
0,New South Wales,6.1,10.9,8484.4
1,Victoria,7.5,9.6,6981.4
2,Queensland,7.4,7.9,5586.3
3,South Australia,5.5,7.1,1878.0
4,Western Australia,7.0,8.5,2965.2
5,Tasmania,11.3,10.1,575.4
6,Northern Territory,4.9,4.2,255.1
7,Australian Capital Territory,6.2,9.6,474.1

In [52]:
chart_2_df["count_sunburn"] = chart_2_df["Proportion (%)_tan"] * chart_2_df["Population at 30 June 2024 ('000)"]*10

In [53]:
chart_2_df

,Region,Proportion (%)_sunburn,Proportion (%)_tan,Population at 30 June 2024 ('000),count_sunburn
0,New South Wales,6.1,10.9,8484.4,924799.6
1,Victoria,7.5,9.6,6981.4,670214.4
2,Queensland,7.4,7.9,5586.3,441317.7
3,South Australia,5.5,7.1,1878.0,133338.0
4,Western Australia,7.0,8.5,2965.2,252042.0
5,Tasmania,11.3,10.1,575.4,58115.4
6,Northern Territory,4.9,4.2,255.1,10714.2
7,Australian Capital Territory,6.2,9.6,474.1,45513.6

In [54]:
chart_2_df.to_csv('chart_2_data.csv', index=False)

In [56]:
engine = create_engine(CONN_STR)

# 4. Upload the data
# name: the table name in Neon
# if_exists: 'replace' creates a new table; 'append' adds to an existing one
chart_2_df.to_sql(name='sunburn_stats', con=engine, if_exists='replace', index=False)

print("Upload Complete! Check your Neon Console SQL Editor.")

Upload Complete! Check your Neon Console SQL Editor.

In [2]:
postcodes_df = pd.read_csv("australian_postcodes.csv")

In [3]:
postcodes_df.head()

,id,postcode,locality,state,long,lat,dc,type,status,sa3,...,altitude,chargezone,phn_code,phn_name,lgaregion,lgacode,electorate,electoraterating,sed_code,sed_name
0,230,200,ANU,ACT,149.11900,-35.277700,NaN,NaN,Updated 3-Dec-2022,NaN,...,NaN,N2,NaN,NaN,Unincorporated ACT,89399.0,Durack,NaN,NaN,NaN
1,21820,200,Australian National University,ACT,149.11890,-35.277700,NaN,NaN,Updated 3-Dec-2022,NaN,...,NaN,N2,NaN,NaN,Unincorporated ACT,89399.0,Durack,NaN,NaN,NaN
2,232,800,DARWIN,NT,130.83668,-12.458684,NaN,NaN,Updated 3-Dec-2022,70101.0,...,NaN,NT1,PHN701,Northern Territory,Darwin Waterfront Precinct,71150.0,Solomon,Inner Metropolitan,70022.0,Port Darwin
3,24049,800,DARWIN CITY,NT,130.83668,-12.458684,NaN,NaN,Updated 3-Dec-2022,70101.0,...,NaN,NT1,PHN701,Northern Territory,Darwin Waterfront Precinct,71150.0,Solomon,Inner Metropolitan,70022.0,Port Darwin
4,233,801,DARWIN,NT,130.83668,-12.458684,NaN,NaN,Updated 3-Dec-2022,70101.0,...,NaN,NT1,PHN701,NaN,Darwin,71000.0,Lingiari,Rural,NaN,NaN

In [4]:
postcodes_df['state'].value_counts()

state
NSW    5592
QLD    3968
VIC    3538
SA     2095
WA     1940
TAS     813
NT      410
ACT     170
Name: count, dtype: int64

In [5]:
postcodes_df.isna().sum()

id                     0
postcode               0
locality               0
state                  0
long                   0
lat                    0
dc                   597
type                 123
status                26
sa3                  161
sa3name              161
sa4                  161
sa4name              161
region                 0
Lat_precise            0
Long_precise           0
SA1_CODE_2021        583
SA1_NAME_2021        583
SA2_CODE_2021        583
SA2_NAME_2021        583
SA3_CODE_2021       1008
SA3_NAME_2021       1008
SA4_CODE_2021       1008
SA4_NAME_2021       1008
RA_2011               41
RA_2016               41
RA_2021             1008
RA_2021_NAME        1008
MMM_2015              41
MMM_2019              41
ced                  833
altitude            5598
chargezone           124
phn_code             345
phn_name             680
lgaregion            446
lgacode              457
electorate           115
electoraterating    1614
sed_code             583
sed_name             583
dtype: int64

In [ ]:
postcodes_df.shapeß

(18526, 41)

In [8]:
postcodes_df_cleaned = postcodes_df[['id','postcode', 'state', 'lat', 'long','locality','Lat_precise','Long_precise']]

In [9]:
postcodes_df.shape

(18526, 41)